### ISSUE TITLE
Insert_ID method with MSSQL Native Driver Returns null

### ISSUE THREAD

**Issue by meeck** [ADOdb/ADOdb#299]
My code not work:
$db->AutoExecute('[TableName]',$fields,'INSERT');      
$id = $db->Insert_ID();  //null

This is because 'preg_match' not work corectly. My workaround with string compare in file adodb-mssqlnative.inc.php line ~572 fix problem.

```
// returns query ID if successful, otherwise false
	function _query($sql,$inputarr=false)
	{
		$this->_errorMsg = false;
		if (is_array($sql)) $sql = $sql[1];
		$insert = false;
		// handle native driver flaw for retrieving the last insert ID    
		if(preg_match('/^\W*insert\s(?:(?:(?:\'\')*\'[^\']+\'(?:\'\')*)|[^;\'])*;?$/i', $sql) 
**or strtolower(substr($sql, 0, 6))=='insert'**) {
			$insert = true;
			$sql .= '; '.$this->identitySQL; // select scope_identity()
		}
		if($inputarr) {
			$rez = sqlsrv_query($this->_connectionID, $sql, $inputarr);
		} else {
			$rez = sqlsrv_query($this->_connectionID,$sql);
		}

		if ($this->debug) ADOConnection::outp("<hr>running query: ".var_export($sql,true)."<hr>input array: ".var_export($inputarr,true)."<hr>result: ".var_export($rez,true));
		if(!$rez) {
			$rez = false;
		} else if ($insert) {
			// retrieve the last insert ID (where applicable)
			while ( sqlsrv_next_result($rez) ) {
				sqlsrv_fetch($rez);
				$this->lastInsertID = sqlsrv_get_field($rez, 0);
			}
		}
		return $rez;
	}
```
My enviroment:
ubuntu 16.04
native driver from microsoft site
mssql 2014 on windows 10 pro
adodb version   v5.20.7  20-Sep-2016
php 7.0.13 (cli)

**Comment by dregad** [comment]
> This is because 'preg_match' not work corectly

In that case the regex should be fixed, and not bypassed by adding a very generic comparison...

Can you please post the exact SQL statement which causes its incorrect detection as an INSERT ?

Is this really specific to PHP7, or is that just the platform you're using ?

**Comment by meeck** [comment]
Hello,

I know, because I wrote a 'workaround' not a 'solution' to the problem.
php7 is my platform. I have not tested on php5.

My query is:
INSERT INTO [CDN].[Kontrahenci] ( KNT_PODMIOTTYP, KNT_KOD, KNT_GLN, KNT_EAN, KNT_GRUPA, KNT_NAZWA1, KNT_NAZWA2, KNT_NAZWA3, KNT_KRAJ, KNT_WOJEWODZTWO, KNT_POWIAT, KNT_GMINA, KNT_ULICA, KNT_NRDOMU, KNT_NRLOKALU, KNT_MIASTO, KNT_KODPOCZTOWY, KNT_POCZTA, KNT_ADRES2, KNT_NIPKRAJ, KNT_NIPE, KNT_NIP, KNT_REGON, KNT_PESEL, KNT_TELEFON1, KNT_TELEFON2, KNT_TELEFONSMS, KNT_FAX, KNT_EMAIL, KNT_URL, KNT_KRAJISO, KNT_ZEZWOLENIE, KNT_KODTRANSAKCJI, KNT_BNAID, KNT_RACHUNEKNR, KNT_IBAN, KNT_RACHUNEKNR0, KNT_OSTYTUL, KNT_OSPLEC, KNT_OSNAZWISKO, KNT_OSKRAJ, KNT_OSWOJEWODZTWO, KNT_OSPOWIAT, KNT_OSGMINA, KNT_OSULICA, KNT_OSNRDOMU, KNT_OSNRLOKALU, KNT_OSMIASTO, KNT_OSKODPOCZTOWY, KNT_OSPOCZTA, KNT_OSADRES2, KNT_OSTELEFON, KNT_OSGSM, KNT_OSEMAIL, KNT_INFORMACJE, KNT_UPUST, KNT_LIMITFLAG, KNT_LIMITKREDYTU, KNT_LIMITPRZETERKREDYTFLAG, KNT_LIMITPRZETERKREDYTWARTOSC, KNT_CENY, KNT_FPLID, KNT_MAXZWLOKA, KNT_TERMINPLAT, KNT_TERMIN, KNT_KONTOODB, KNT_KONTODOST, KNT_KATID, KNT_KATZAKID, KNT_BLOKADADOK, KNT_LIMITKREDYTUWAL, KNT_LIMITKREDYTUWYKORZYSTANY, KNT_NIEROZLICZAC, KNT_PODATEKVAT, KNT_FINALNY, KNT_FINALNYWEGIEL, KNT_EXPORT, KNT_RODZAJ, KNT_RODZAJ_DOSTAWCA, KNT_RODZAJ_ODBIORCA, KNT_RODZAJ_KONKURENCJA, KNT_RODZAJ_PARTNER, KNT_RODZAJ_POTENCJALNY, KNT_MEDIALNY, KNT_MALYPOD, KNT_ROLNIK, KNT_NIEAKTYWNY, KNT_CHRONIONY, KNT_OPIS, KNT_ODBIORCAID, KNT_OPIEKUNTYP, KNT_OPIEKUNKSIEGTYP, KNT_OPIEKUNKSIEGID, KNT_OPIEKUNKSIEGDOMYSLNY, KNT_OPIEKUNPIKTYP, KNT_OPIEKUNPIKID, KNT_OPIEKUNPIKDOMYSLNY, KNT_TERMINZWROTUKAUCJI, KNT_NALICZAJPLATNOSC, KNT_ZAKAZDOKUMENTOWHAMAG, KNT_ZGODANAEFAKTURY, KNT_TYPWYMIANY, KNT_POWIAZANYUOV, KNT_METODAKASOWA, KNT_IMPORTROWID, KNT_OPEZALID, KNT_STAZALID, KNT_TS_ZAL, KNT_OPEMODID, KNT_STAMODID, KNT_TS_MOD, KNT_GIDNUMER, KNT_FCZYNNOSCI, KNT_FCZESCI, KNT_KORKRAJ, KNT_KORMIASTO, KNT_KORKODPOCZTOWY, KNT_KORPOCZTA, KNT_KORULICA, KNT_KORNRDOMU, KNT_NIENALICZAJODSETEK, KNT_ESKLEP, KNT_ZWOLNIONYZAKCYZY, KNT_WINDYKACJAOSOBAID, KNT_WINDYKACJAEMAIL, KNT_WINDYKACJATELEFONSMS, KNT_KOMORNIK, KNT_NADID, KNT_WALUTA, KNT_ALGORYTM, KNT_NIEUWZGLVATZD, KNT_GLID ) VALUES ( 1, '', '', '', '', 'Śmieszna sprawęcja spółka złoło', '', '', 'Polska', '', '', '', 'Śliska', '5', '7B', 'Kocia Górka', '02-444', 'Kocica 1', '', 'PL', '2211345149', '2211345149', '', '', '223001117', '451003322', '', '', 'tester@kawalawa.pl', 'www.kawalawa.pl', '', '', '', null, 'PL36215002573834969436264563', 1, '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, '', '', null, null, 0, '', 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, null, null, 1, null, null, 0, 60, 0, 0, 0, null, 0, 0, '', 0, 0, '2016-12-01T11:13:12', 0, 0, '2016-12-01T11:13:12', 0, 1, 0, null, null, null, null, null, null, 0, 0, 0, null, '', '', 0, null, 'EUR', 0, 0, null )

**Comment by dregad** [comment]
The function fails due to empty string values `''` not being matched by the regex.

I believe this issue has already been fixed in the master branch, see #185.

**Comment by dregad** [comment]
I just realized that I never actually applied the modified regex as a hotfix for the 5.20 branch, as mentioned in https://github.com/ADOdb/ADOdb/issues/185#issuecomment-169592672. This will be included in upcoming 5.20.8.

**Comment by meeck** [comment]
Hello, 
I tested on 5.20.9 and problem still exists. The query not match regex. 
I verified on https://regex101.com/r/yU0gD9/4 too.

**Comment by meeck** [comment]
I found it! this is because square brackets in table name.

**Comment by dregad** [comment]
Please open a separate issue, referencing this one (and #185 too), for follow-up. Thanks !
