### ISSUE TITLE
'each()' function is deprecated

### ISSUE THREAD

**Issue by VincentP-HANFF** [ADOdb/ADOdb#623]
Hello,

I'm using AdoDb for connection related to an historical database in my company, and then doctrine for the website own database.

Symfony show me a deprecations for using the ``each()`` function as it is deprecated since PHP 7.2.

> php | Deprecated: The each() function is deprecated. This message will be suppressed on further calls

The problem is from this function ```getAll()``` which may use the ```each()```function of PHP.

My code is the following : 
```
$datas = $this->_db->Execute($query, $array_article_number)->getAll();
```

So what could i use instead of ```getAll()``` which is not deprecated in PHP 7.2 ?

**Comment by dregad** [comment]
Which version of ADOdb are you using ? This problem has been fixed a long time ago ([5.20.12](https://github.com/ADOdb/ADOdb/blob/master/docs/changelog.md#52012---30-mar-2018)), see #373.

**Comment by geri777** [comment]
I still get this error with a new composer installation. 
I find "each(" in 8 files, 13 times.

**Comment by dregad** [comment]
I see no reason to reopen, there are no occurences of `each` in the current codebase - you must be looking at old code.

```
~/dev/adodb(master)$ git grep -w each\( -- *.php
~/dev/adodb(master)$ git checkout hotfix/5.20 
Switched to branch 'hotfix/5.20'
Your branch is up to date with 'origin/hotfix/5.20'.
~/dev/adodb(hotfix/5.20)$ git grep -w each\( -- *.php
```
