### ISSUE TITLE
mysqli: uncaught exception calling execute() with empty SQL

### ISSUE THREAD

**Issue by NathanGibbs3** [ADOdb/ADOdb#945]
### Description
On PHP 8x Only, this error gets thrown for the mysqli driver.
`ValueError: mysqli_query(): Argument #2 ($query) cannot be empty`

Testing on PHP 8.x with ADOdb all versions between
 - 5.20.12 https://app.travis-ci.com/github/NathanGibbs3/BASE/builds/261817858
 - 5.22.4 https://app.travis-ci.com/github/NathanGibbs3/BASE/builds/261971663

Relevant error messages and stack trace from the 5.22.4 tests.
https://app.travis-ci.com/github/NathanGibbs3/BASE

ValueError: mysqli_query(): Argument #2 ($query) cannot be empty
1) dbTest::testbaseExecuteNULLSQLReturnsExpected

/home/travis/build/NathanGibbs3/BASE/build/adodb/ADOdb-5.22.4/drivers/adodb-mysqli.inc.php:1365
/home/travis/build/NathanGibbs3/BASE/build/adodb/ADOdb-5.22.4/adodb.inc.php:1550
/home/travis/build/NathanGibbs3/BASE/build/adodb/ADOdb-5.22.4/drivers/adodb-mysqli.inc.php:1116
/home/travis/build/NathanGibbs3/BASE/includes/base_db.inc.php:305
/home/travis/build/NathanGibbs3/BASE/tests/PhpUnit/idbTest.php:429

### Environment
- ADOdb version: 5.20.12 - 5.22.4
- Driver or Module: mysqli
- Database type and version: Mysql
- PHP version: 8x
- Platform: 

* [x] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest) / **hotfix/5.22** branch

### Steps to reproduce
Call `Execute()` with an empty sql string on mysqli, it throws a ValueError exception on PHP 8x, A notice on everything else.
Call `Execute()` with an empty sql string on postgres, it throws a notice on everything.

### Expected behavior
Expecting empty SQL to throw a notice.

**Comment by dregad** [comment]
There is a large number of PHP 8 issues fixed in upcoming 5.22.5 (to be released shortly, I'm actually working on it), so it would be great if you could confirm if the problem is fixed in the *hotfix/5.22* branch.

**Comment by dregad** [comment]
Nevermind, this is easily reproducible with
```php
$db = ADONewConnection('mysqli');
$db->connect(...);
var_dump($db->execute(''));
```
Returns *false* on php 7.x, throws ValueError exception on PHP 8

And the problem is **not** fixed in hotfix/5.22 branch.

**Comment by dregad** [comment]
I'll hold off releasing 5.22.5 so I can include a fix for this bug in it.

**Comment by NathanGibbs3** [comment]
Just tested the hotfix/5.22 branch in CI.
https://app.travis-ci.com/github/NathanGibbs3/BASE/jobs/599380996
Confirmed, not fixed in hotfix/5.22 branch.

Adjusting my project's CI Environment setup code to pull a branch straight from the ADOdb repo was worth it. 💻 😄

**Comment by NathanGibbs3** [comment]
Try something like this also as an invalid SQL test.

$db = ADONewConnection('mysqli');
$db->connect(...);
var_dump($db->execute('SELEXT * FROM table'));
var_dump($$db->ErrorMsg());

I'm getting different returns from ErrorMsg between PHP 8x and older versions.

**Comment by NathanGibbs3** [comment]
I'll have test results within the hour. Thanks. :smile:

**Comment by NathanGibbs3** [comment]
This bug has definitely been fixed.
https://app.travis-ci.com/github/NathanGibbs3/BASE
I'll get you some more concrete test data for #947 and post it in that bug's thread.
Thank You. :smile:
